### ISSUE TITLE
flight mode button order for Rover

### ISSUE THREAD

**Issue by rmackay9** [HefnySco/andruav_webclient#3]
![image](https://user-images.githubusercontent.com/1498098/179444348-d92fa613-0093-4f9f-91dd-de9a18a08d08.png)
Similar to issue https://github.com/HefnySco/andruav_webclient/issues/2 I think we could improve the button placement and/or order for Rovers and boats.

For Rover/Boat I think the most commonly used modes are:

Manual, Acro, RTL, Auto and Hold.  For Boats Loiter is also very popular
Next most common: SmartRTL and Guided

.. but I should say, more important than all the above is just adding Acro mode to the list of modes.  Everything else is just a suggestion.

**Comment by HefnySco** [comment]
I agree the buttons need a redesign. Sadly I am not a UI expert as well.
I will expose the popular buttons so that at least it is more convenient.

**Comment by rmackay9** [comment]
@HefnySco,

Great, thanks.  Yeah, in the end the most important thing for me was to get Acro on the list of buttons... and for boat we need Loiter.

**Comment by HefnySco** [comment]
![Screenshot from 2022-07-21 05-29-49](https://user-images.githubusercontent.com/4184373/180124609-1caba001-096f-48f8-89e6-4f3beeec6b85.png)

will work with Andruav_AP ver_5.02.00 and later.
